main:- consult('interface.pl'), menu, !.

menu :- repeat,
	write('=== MENU ==='), nl,
	write('1. Carregar base padrão'), nl,
	write('2. Inserir novos dados'), nl,
	write('3. Tios e tias'), nl,
	write('4. Avós e avôs'), nl,
	write('5. Primos e primas'), nl,
	write('6. Sobrinhos e sobrinhas'), nl,
	write('7. Irmãos e irmãs'), nl,
	write('8. Filhos e filhas'), nl,
	write('9. Netos e netas'), nl,
	write('10. Pais e mães'), nl,
	write('11. Cônjuges'), nl,
	write('0. Exit'), nl,
	read(X),
	interface(X),
	X==0,
	!.
